name: Starting Future Docker Container for Mongo

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: checking version of Tools
        run: |
          node -v
          npm -v
          aws --version
